# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  xxxSITE_KEYxxx:
    env:
      db_password: xxxKINSTA_DB_PASSWORDxxx
      auth_key: "generateme"
      secure_auth_key: "generateme"
      logged_in_key: "generateme"
      nonce_key: "generateme"
      auth_salt: "generateme"
      secure_auth_salt: "generateme"
      logged_in_salt: "generateme"
      nonce_salt: "generateme"
      # TODO: If you site is protected by HTTP basic auth.
      # http_basic_auth_username: xxxHTTP_BASIC_AUTH_USERNAMExxx
      # http_basic_auth_password: xxxHTTP_BASIC_AUTH_PASSWORDxxx
