# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  xxxSITE_KEYxxx:
    site_hosts:
      - canonical: xxxSTAGING_DOMAINxxx
    local_path: ../bedrock # path targeting local Bedrock site directory (relative to Ansible root)
    repo: xxxBEDROCK_REPOxxx
    branch: staging
    env:
      # Note that db_password is defined in `group_vars/<env>/vault.yml`
      db_prefix: xxxDB_PREFIXxxx
      db_name: xxxKINSTA_SSH_USERNAMExxx
      db_user: xxxKINSTA_SSH_USERNAMExxx
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed # Doesn't matter. Just to keep Trellis happy
    cache:
      enabled: false
    # TODO: Change this to sage theme name
    # See: `deploy-hooks/build-before.yml`
    # sage: sage
