# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: admin

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    # Keys here is useless. They never uploaded to Kinsta.
    # Keeping it as an empty array to make Trellis happy.
    # Use my.kinsta.com to upload your SSH public keys instead.
    keys: []
  # Admin user is useless. No such user on Kinsta.
  # Keeping it as it is to make Trellis happy.
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys: []

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php7.4-fpm *"
